#!/bin/bash
# install firewalld

function printcolor(){


   case $1 in
    "green")
  echo -e "\033[0;32m $2\033[0m"
        ;;
"red")
  echo -e "\033[0;31m $2\033[0m"
        ;;
 "*")
  echo -e "\033[0;31m $2\033[0m"
        ;;
      esac
}

function isactive(){
  is_active=$(systemctl is-active $1)

if [ $is_active = "active" ]
then
printcolor "green" "$1 is active"
else
  printcolor "red" "$1 is not active"
#exit 1
  fi

}


function checkItem(){

  if [[ $web_page = *$2* ]]
then
  printcolor "green" "$2 data loaded"
  else
    printcolor "red" "$2 data not loaded"
    fi
}

function portCheck(){
  firewalld_ports=$(sudo firewall-cmd --list-all --zone=public | grep ports)

if [[ firewalld_ports = *$1* ]]
then
  printcolor "green" "$1 is configured"
  else
    printcolor "red" "$1 configured"
    #exit 1
  fi


}

printcolor "green" "Installing firewalld"
sudo yum install -y firewalld
sudo service firewalld start
sudo systemctl enable firewalld

isactive firewalld


printcolor "green" "Install mariadb"
sudo yum install -y mariadb-server
sudo service mariadb start
sudo systemctl enable mariadb
isactive mariadb


printcolor "green" "enalbe port address"
sudo firewall-cmd --permanent --zone=public --add-port=3306/tcp
sudo firewall-cmd --reload

portCheck 3306

printcolor "green" "configure db"
cat <<EOF > configure_db.sql
CREATE DATABASE ecomdb;
CREATE USER 'ecomuser'@'localhost' IDENTIFIED BY 'ecompassword';
GRANT ALL PRIVILEGES ON *.* TO 'ecomuser'@'localhost';
FLUSH PRIVILEGES;
EOF

sudo mysql < configure_db.sql

cat > db-load-script.sql <<-EOF
USE ecomdb;
CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;

INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");

EOF

sudo mysql < db-load-script.sql

product=$(sudo mysql -e "use ecomdb; select * from products;")
if [[ $product = *Laptop* ]]
then
  printcolor "green" "inventory data loaded"
  else
    printcolor "red" "inventory data not loaded"
    fi

printcolor "green" "install php mysql"
sudo yum install -y httpd php php-mysql
sudo firewall-cmd --permanent --zone=public --add-port=80/tcp
sudo firewall-cmd --reload
portCheck 80

sudo sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf

printcolor "green" "install httpd"
sudo service httpd start
sudo systemctl enable httpd
isactive httpd

printcolor "green" "install git"
sudo yum install -y git
sudo git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/

sudo sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php

print "green" "all set"


web_page=$(curl http://localhost)


for item in Laptop Drone
do
checkItem "$web_page" $item
done
